# Generated by Django 3.0.5 on 2020-05-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_mlmodelexamples'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='api_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
