# Generated by Django 3.0.5 on 2020-05-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_auto_20200502_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodelexamples',
            name='fields',
        ),
        migrations.AddField(
            model_name='mlmodelexamples',
            name='classes',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mlmodelexamples',
            name='xlabels',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mlmodelexamples',
            name='ylabel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mlmodelexamples',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
