# Generated by Django 3.0.5 on 2020-05-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0005_auto_20200502_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodelexamples',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
    ]
